sqlplus / as sysdba @/home/oracle/import.sql

SET ECHO ON
SET FEEDBACK ON
SET VERIFY OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

SPOOL create_sankhya.log

-- Configuração de Segurança Inicial
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Remoção de objetos existentes com tratamento de erros 
DROP USER SANKHYA CASCADE;
DROP TABLESPACE SANKHYA INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE SANKIND INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE SANKLOB INCLUDING CONTENTS AND DATAFILES;

-- Criação das Tablespaces
CREATE TABLESPACE SANKHYA
DATAFILE '/opt/oracle/oradata/ORCL/SANKHYA.DBF'
SIZE 10G
AUTOEXTEND ON NEXT 1G
MAXSIZE UNLIMITED
SEGMENT SPACE MANAGEMENT AUTO;

ALTER DATABASE DATAFILE '/opt/oracle/oradata/ORCL/SANKHYA.DBF' AUTOEXTEND ON MAXSIZE UNLIMITED;

-- impdp system/tecsis ATTACH=SYS_IMPORT_SCHEMA_01

CREATE TABLESPACE SANKIND
DATAFILE '/opt/oracle/oradata/ORCL/SANKIND.DBF'
SIZE 10G
AUTOEXTEND ON NEXT 1G
MAXSIZE UNLIMITED
SEGMENT SPACE MANAGEMENT AUTO;
ALTER DATABASE DATAFILE '/opt/oracle/oradata/ORCL/SANKIND.DBF' AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE TABLESPACE SANKLOB
DATAFILE '/opt/oracle/oradata/ORCL/SANKLOB.DBF'
SIZE 10G
AUTOEXTEND ON NEXT 1G
MAXSIZE UNLIMITED
SEGMENT SPACE MANAGEMENT AUTO;
ALTER DATABASE DATAFILE '/opt/oracle/oradata/ORCL/SANKLOB.DBF' AUTOEXTEND ON MAXSIZE UNLIMITED;


-- Criação do Usuário
CREATE USER SANKHYA IDENTIFIED BY "tecsis"
  DEFAULT TABLESPACE SANKHYA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON SANKHYA
  QUOTA UNLIMITED ON SANKIND
  QUOTA UNLIMITED ON SANKLOB
  PASSWORD EXPIRE
  ACCOUNT UNLOCK;


--   STARTUP MOUNT;
-- ALTER SYSTEM ENABLE RESTRICTED SESSION;
-- ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0;
-- ALTER DATABASE OPEN;
-- ALTER DATABASE CHARACTER SET INTERNAL_USE WE8MSWIN1252;
-- SHUTDOWN IMMEDIATE;
-- STARTUP;

GRANT CONNECT, RESOURCE, DBA TO SANKHYA; 
GRANT ALL PRIVILEGES TO SANKHYA; 
GRANT DBA TO SANKHYA;
GRANT SELECT ON DBA_TRIGGERS TO SANKHYA; 
GRANT SELECT ON DBA_OBJECTS TO SANKHYA; 
GRANT SELECT ON V_$SESSION TO SANKHYA; 
GRANT SELECT ON V_$INSTANCE TO SANKHYA; 
grant execute on dbms_crypto to SANKHYA;
grant execute on dbms_OUTPUT to SANKHYA;
grant execute on DBMS_OBFUSCATION_TOOLKIT to SANKHYA;

-- Concessão de Privilégios
GRANT 
  CREATE SESSION,
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE PROCEDURE,
  CREATE TRIGGER,
  CREATE SYNONYM,
  CREATE MATERIALIZED VIEW
TO SANKHYA;

GRANT SELECT_CATALOG_ROLE TO SANKHYA;
GRANT EXECUTE ON DBMS_LOCK TO SANKHYA;
GRANT DEBUG CONNECT SESSION TO SANKHYA;

-- Configurações Adicionais
ALTER USER SANKHYA DEFAULT ROLE ALL;
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;

-- Desativar HTTP
BEGIN
  DBMS_XDB.SETHTTPPORT(0);
  COMMIT;
END;
/

COMMIT;

SPOOL OFF;

PROMPT **********************************************
PROMPT * Script executado com sucesso!               *
PROMPT * Verifique o arquivo create_sankhya.log      *
PROMPT * Usuário: SANKHYA                            *
PROMPT * Senha: tecsis                      		 *
PROMPT **********************************************