SET ECHO ON
SET FEEDBACK ON
SET VERIFY OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

SPOOL create_sankhya.log

-- Habilita operações administrativas
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- =============================
-- Remoção segura de objetos
-- =============================

BEGIN
  FOR tbs IN (SELECT tablespace_name FROM dba_tablespaces WHERE tablespace_name IN ('SANKHYA','SANKIND','SANKLOB')) LOOP
    EXECUTE IMMEDIATE 'DROP TABLESPACE ' || tbs.tablespace_name || ' INCLUDING CONTENTS AND DATAFILES';
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro ao excluir tablespaces (ignorado): ' || SQLERRM);
END;
/

BEGIN
  IF EXISTS (SELECT 1 FROM dba_users WHERE username = 'SANKHYA') THEN
    EXECUTE IMMEDIATE 'DROP USER SANKHYA CASCADE';
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro ao excluir usuário SANKHYA (ignorado): ' || SQLERRM);
END;
/

-- =============================
-- Criação das Tablespaces
-- =============================

CREATE TABLESPACE SANKHYA
  DATAFILE '/opt/oracle/oradata/ORCL/SANKHYA.DBF'
  SIZE 10G
  AUTOEXTEND ON NEXT 1G
  MAXSIZE UNLIMITED
  SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE SANKIND
  DATAFILE '/opt/oracle/oradata/ORCL/SANKIND.DBF'
  SIZE 10G
  AUTOEXTEND ON NEXT 1G
  MAXSIZE UNLIMITED
  SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE SANKLOB
  DATAFILE '/opt/oracle/oradata/ORCL/SANKLOB.DBF'
  SIZE 10G
  AUTOEXTEND ON NEXT 1G
  MAXSIZE UNLIMITED
  SEGMENT SPACE MANAGEMENT AUTO;

-- =============================
-- Criação do usuário SANKHYA
-- =============================

CREATE USER SANKHYA IDENTIFIED BY "tecsis"
  DEFAULT TABLESPACE SANKHYA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON SANKHYA
  QUOTA UNLIMITED ON SANKIND
  QUOTA UNLIMITED ON SANKLOB
  PASSWORD EXPIRE
  ACCOUNT UNLOCK;

-- =============================
-- Concessão de privilégios
-- =============================

GRANT CONNECT, RESOURCE, DBA TO SANKHYA;
GRANT ALL PRIVILEGES TO SANKHYA;
GRANT SELECT ON DBA_TRIGGERS TO SANKHYA;
GRANT SELECT ON DBA_OBJECTS TO SANKHYA;
GRANT SELECT ON V_$SESSION TO SANKHYA;
GRANT SELECT ON V_$INSTANCE TO SANKHYA;

GRANT EXECUTE ON DBMS_CRYPTO TO SANKHYA;
GRANT EXECUTE ON DBMS_OUTPUT TO SANKHYA;
GRANT EXECUTE ON DBMS_OBFUSCATION_TOOLKIT TO SANKHYA;
GRANT EXECUTE ON DBMS_LOCK TO SANKHYA;

GRANT 
  CREATE SESSION,
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE PROCEDURE,
  CREATE TRIGGER,
  CREATE SYNONYM,
  CREATE MATERIALIZED VIEW,
  DEBUG CONNECT SESSION,
  SELECT_CATALOG_ROLE
TO SANKHYA;

ALTER USER SANKHYA DEFAULT ROLE ALL;

-- Limita bloqueios por tentativas erradas de login
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;

-- =============================
-- Configuração Adicional: Desativa porta HTTP
-- =============================
BEGIN
  DBMS_XDB.SETHTTPPORT(0);
  COMMIT;
END;
/

COMMIT;

SPOOL OFF;

PROMPT **********************************************
PROMPT * Script executado com sucesso!              *
PROMPT * Verifique o arquivo create_sankhya.log     *
PROMPT * Usuário: SANKHYA                           *
PROMPT * Senha: tecsis                              *
PROMPT **********************************************
