SET ECHO ON
SET FEEDBACK ON
SET VERIFY OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

SPOOL create_sankhya.log

-- Ativa permissões para DROP de usuários padrão
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- Remover o usuário SANKHYA, se existir
BEGIN
  EXECUTE IMMEDIATE 'DROP USER SANKHYA CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01918 THEN -- Usuário não existe
      RAISE;
    END IF;
END;
/

-- Remover tablespace SANKHYA, se existir
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLESPACE SANKHYA INCLUDING CONTENTS AND DATAFILES';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -00959 THEN -- Tablespace não existe
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLESPACE SANKIND INCLUDING CONTENTS AND DATAFILES';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -00959 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLESPACE SANKLOB INCLUDING CONTENTS AND DATAFILES';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -00959 THEN
      RAISE;
    END IF;
END;
/

-- Criação das Tablespaces com tamanho seguro para evitar erro ORA-19502
CREATE TABLESPACE SANKHYA
DATAFILE '/u01/app/oracle/oradata/ORCL/SANKHYA.DBF'
SIZE 1G
AUTOEXTEND ON NEXT 100M
MAXSIZE 5G
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE SANKIND
DATAFILE '/u01/app/oracle/oradata/ORCL/SANKIND.DBF'
SIZE 1G
AUTOEXTEND ON NEXT 100M
MAXSIZE 5G
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE SANKLOB
DATAFILE '/u01/app/oracle/oradata/ORCL/SANKLOB.DBF'
SIZE 1G
AUTOEXTEND ON NEXT 100M
MAXSIZE 5G
SEGMENT SPACE MANAGEMENT AUTO;

-- Criação do Usuário
CREATE USER SANKHYA IDENTIFIED BY "tecsis"
  DEFAULT TABLESPACE SANKHYA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON SANKHYA
  QUOTA UNLIMITED ON SANKIND
  QUOTA UNLIMITED ON SANKLOB
  PASSWORD EXPIRE
  ACCOUNT UNLOCK;

-- Concessão de Privilégios
GRANT CONNECT, RESOURCE, DBA TO SANKHYA; 
GRANT ALL PRIVILEGES TO SANKHYA; 
GRANT DBA TO SANKHYA;
GRANT SELECT ON DBA_TRIGGERS TO SANKHYA; 
GRANT SELECT ON DBA_OBJECTS TO SANKHYA; 
GRANT SELECT ON V_$SESSION TO SANKHYA; 
GRANT SELECT ON V_$INSTANCE TO SANKHYA; 
GRANT EXECUTE ON DBMS_CRYPTO TO SANKHYA;
GRANT EXECUTE ON DBMS_OUTPUT TO SANKHYA;
GRANT EXECUTE ON DBMS_OBFUSCATION_TOOLKIT TO SANKHYA;
GRANT EXECUTE ON DBMS_LOCK TO SANKHYA;
GRANT DEBUG CONNECT SESSION TO SANKHYA;

GRANT 
  CREATE SESSION,
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE PROCEDURE,
  CREATE TRIGGER,
  CREATE SYNONYM,
  CREATE MATERIALIZED VIEW
TO SANKHYA;

GRANT SELECT_CATALOG_ROLE TO SANKHYA;

-- Configurações adicionais
ALTER USER SANKHYA DEFAULT ROLE ALL;
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;

-- Desativar porta HTTP
BEGIN
  DBMS_XDB.SETHTTPPORT(0);
  COMMIT;
END;
/

COMMIT;

SPOOL OFF;

PROMPT **********************************************
PROMPT * Script executado com sucesso!              *
PROMPT * Verifique o arquivo create_sankhya.log     *
PROMPT * Usuário: SANKHYA                           *
PROMPT * Senha: tecsis                              *
PROMPT **********************************************
